backend:
  name: git-gateway
  repo: RedCiudadana/TodoEstaEnQuetzaltenango
  branch: main
  identity_url: https://auth.decapbridge.com/sites/f6c98682-1f4c-48ef-9994-0a248fe25dec
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "negocios"
    label: "Negocios"
    folder: "src/content/negocios"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del Negocio", name: "nombre", widget: "string" }
      - 
        label: "Categorías"
        name: "categorias"
        widget: "list"
        field:
          label: "Categoría"
          name: "categoria"
          widget: "string"
      - { label: "Fotografía del Negocio", name: "foto_negocio", widget: "image", required: false }
      - { label: "Municipio", name: "municipio", widget: "string" }
      - { label: "Dirección", name: "direccion", widget: "string" }
      - { label: "Ubicación en Google Maps", name: "ubicacion", widget: "string" }
      - { label: "Descripción del Negocio", name: "descripcion", widget: "text" }
      - { label: "Teléfono", name: "telefono", widget: "string" }
      - { label: "Correo Electrónico", name: "correo_electronico", widget: "string" }
      - { label: "Menú o Catálogo", name: "menu_catalogo", widget: "string", required: false }
      - { label: "Sitio Web", name: "sitio_web", widget: "string" }
      - { label: "Pago en Efectivo", name: "pago_efectivo", widget: "boolean", default: false }
      - { label: "Pago con Tarjeta", name: "pago_tarjeta", widget: "boolean", default: false }
      - { label: "Pago por Transferencia", name: "pago_transferencia", widget: "boolean", default: false }
      - { label: "Lunes a Viernes", name: "horario_lunes_viernes", widget: "boolean", default: false }
      - { label: "Sábado", name: "horario_sabado", widget: "boolean", default: false }
      - { label: "Domingo", name: "horario_domingo", widget: "boolean", default: false }
      - { label: "Facebook", name: "facebook", widget: "string", required: false }
      - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - { label: "TikTok", name: "tiktok", widget: "string", required: false }
