backend:
  name: git-gateway
  repo: RedCiudadana/Conecta-Futuro
  branch: main
  identity_url: https://auth.decapbridge.com/sites/e0f05e32-27b9-4041-9b01-a06878fc1d6b
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "negocios"
    label: "Negocios"
    folder: "src/content/negocios"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del Negocio", name: "nombre", widget: "string" }
      - { label: "Categoría", name: "categoria", widget: "string" }
      - { label: "Municipio", name: "municipio", widget: "string" }
      - { label: "Dirección y ubicación en Google Maps", name: "direccion", widget: "string" }
      - { label: "Descripción del Negocio", name: "descripcion", widget: "text" }
      - { label: "Teléfono", name: "telefono", widget: "string" }
      - { label: "Correo Electrónico", name: "correo_electronico", widget: "string" }
      - { label: "Sitio Web", name: "sitio_web", widget: "string" }
      - { label: "Pago en Efectivo", name: "pago_efectivo", widget: "boolean", default: false }
      - { label: "Pago con Tarjeta", name: "pago_tarjeta", widget: "boolean", default: false }
      - { label: "Pago por Transferencia", name: "pago_transferencia", widget: "boolean", default: false }
      - { label: "Lunes a Viernes", name: "horario_lunes_viernes", widget: "boolean", default: false }
      - { label: "Sábado", name: "horario_sabado", widget: "boolean", default: false }
      - { label: "Domingo", name: "horario_domingo", widget: "boolean", default: false }
      - { label: "Facebook", name: "facebook", widget: "string", required: false }
      - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - { label: "TikTok", name: "tiktok", widget: "string", required: false }
